/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#47664a",
        "primary-dim": "#3b5a3f",
        "primary-container": "#c8ecc8",
        "primary-fixed": "#c8ecc8",
        "primary-fixed-dim": "#badeba",
        "on-primary": "#e9ffe6",
        "on-primary-container": "#3a593d",
        "on-primary-fixed": "#27462c",
        "on-primary-fixed-variant": "#436347",
        "secondary": "#54634e",
        "secondary-dim": "#485743",
        "secondary-container": "#d7e8cd",
        "secondary-fixed": "#d7e8cd",
        "secondary-fixed-dim": "#c9dabf",
        "on-secondary": "#edfee2",
        "on-secondary-container": "#475641",
        "on-secondary-fixed": "#354330",
        "on-secondary-fixed-variant": "#51604b",
        "tertiary": "#4a664a",
        "tertiary-dim": "#3f5a3f",
        "tertiary-container": "#d4f4d0",
        "tertiary-fixed": "#d4f4d0",
        "tertiary-fixed-dim": "#c6e5c3",
        "on-tertiary": "#e9ffe5",
        "on-tertiary-container": "#425d43",
        "on-tertiary-fixed": "#304b31",
        "on-tertiary-fixed-variant": "#4c684c",
        "background": "#fcf9f8",
        "on-background": "#323232",
        "surface": "#fcf9f8",
        "surface-dim": "#dbdad9",
        "surface-bright": "#fcf9f8",
        "surface-variant": "#e4e2e2",
        "surface-tint": "#47664a",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e2",
        "on-surface": "#323232",
        "on-surface-variant": "#5f5f5f",
        "outline": "#7b7a7a",
        "outline-variant": "#b3b2b1",
        "inverse-surface": "#0e0e0e",
        "inverse-on-surface": "#9e9c9c",
        "inverse-primary": "#cdf2cd",
        "error": "#a73b21",
        "error-dim": "#791903",
        "error-container": "#fd795a",
        "on-error": "#fff7f6",
        "on-error-container": "#6e1400",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        "card": "0 20px 40px rgba(50,50,50,0.06)",
        "card-hover": "0 20px 40px rgba(50,50,50,0.10)",
        "nav": "0 20px 40px rgba(50,50,50,0.06)",
        "sage": "0 15px 30px rgba(71,102,74,0.2)",
        "sage-lg": "0 20px 40px rgba(71,102,74,0.3)",
      },
    },
  },
  plugins: [],
}
